# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cat_dog_pb2 as cat__dog__pb2


class Animal_classifStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cat_or_dog = channel.unary_unary(
                '/cat_dog.Animal_classif/cat_or_dog',
                request_serializer=cat__dog__pb2.ImageRequest.SerializeToString,
                response_deserializer=cat__dog__pb2.AnimalResponse.FromString,
                )


class Animal_classifServicer(object):
    """The greeting service definition.
    """

    def cat_or_dog(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Animal_classifServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cat_or_dog': grpc.unary_unary_rpc_method_handler(
                    servicer.cat_or_dog,
                    request_deserializer=cat__dog__pb2.ImageRequest.FromString,
                    response_serializer=cat__dog__pb2.AnimalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cat_dog.Animal_classif', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Animal_classif(object):
    """The greeting service definition.
    """

    @staticmethod
    def cat_or_dog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cat_dog.Animal_classif/cat_or_dog',
            cat__dog__pb2.ImageRequest.SerializeToString,
            cat__dog__pb2.AnimalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
