# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cat_dog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cat_dog.proto',
  package='cat_dog',
  syntax='proto3',
  serialized_options=b'B\013CatDogProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcat_dog.proto\x12\x07\x63\x61t_dog\" \n\x0e\x41nimalResponse\x12\x0e\n\x06\x61nimal\x18\x01 \x01(\t\"i\n\x0cImageRequest\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x11\n\timage_red\x18\x03 \x01(\x0c\x12\x13\n\x0bimage_green\x18\x04 \x01(\x0c\x12\x12\n\nimage_blue\x18\x05 \x01(\x0c\x32P\n\x0e\x41nimal_classif\x12>\n\ncat_or_dog\x12\x15.cat_dog.ImageRequest\x1a\x17.cat_dog.AnimalResponse\"\x00\x42\x15\x42\x0b\x43\x61tDogProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_ANIMALRESPONSE = _descriptor.Descriptor(
  name='AnimalResponse',
  full_name='cat_dog.AnimalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='animal', full_name='cat_dog.AnimalResponse.animal', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=58,
)


_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='cat_dog.ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='cat_dog.ImageRequest.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='cat_dog.ImageRequest.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_red', full_name='cat_dog.ImageRequest.image_red', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_green', full_name='cat_dog.ImageRequest.image_green', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_blue', full_name='cat_dog.ImageRequest.image_blue', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['AnimalResponse'] = _ANIMALRESPONSE
DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnimalResponse = _reflection.GeneratedProtocolMessageType('AnimalResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANIMALRESPONSE,
  '__module__' : 'cat_dog_pb2'
  # @@protoc_insertion_point(class_scope:cat_dog.AnimalResponse)
  })
_sym_db.RegisterMessage(AnimalResponse)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'cat_dog_pb2'
  # @@protoc_insertion_point(class_scope:cat_dog.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)


DESCRIPTOR._options = None

_ANIMAL_CLASSIF = _descriptor.ServiceDescriptor(
  name='Animal_classif',
  full_name='cat_dog.Animal_classif',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=167,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='cat_or_dog',
    full_name='cat_dog.Animal_classif.cat_or_dog',
    index=0,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_ANIMALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANIMAL_CLASSIF)

DESCRIPTOR.services_by_name['Animal_classif'] = _ANIMAL_CLASSIF

# @@protoc_insertion_point(module_scope)
